#!/bin/python3

import sys
import os
import subprocess

arguments = sys.argv

flavor = arguments[1]

image = arguments[2]

currentDirectory = os.getcwd()

try:
    
    if flavor == "latte":
        subprocess.run("cd {} ; magick {} /opt/catppuccinifier/flavors/latte-hald-clut.png -hald-clut {}-{}".format(currentDirectory, image, flavor, image), shell=True)

    elif flavor == "frappe":
        subprocess.run("cd {} ; magick {} /opt/catppuccinifier/flavors/frappe-hald-clut.png -hald-clut {}-{}".format(currentDirectory, image, flavor, image), shell=True)

    elif flavor == "macchiato":
        subprocess.run("cd {} ; magick {} /opt/catppuccinifier/flavors/macchiato-hald-clut.png -hald-clut {}-{}".format(currentDirectory, image, flavor, image), shell=True)

    elif flavor == "mocha":
        subprocess.run("cd {} ; magick {} /opt/catppuccinifier/flavors/mocha-hald-clut.png -hald-clut {}-{}".format(currentDirectory, image, flavor, image), shell=True)

    else:
        
        print("Flavor not found")

except Exception as e:
    
    print(type(e))