[package]
name = "catppuccinifier-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
colored = "2.0.0"
dirs = "5.0.0"
clap = { version = "4.2.7", features = ["derive", "cargo"] }
substring = "1.4.5"